apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    dynatrace.com/operator: dynakube
    internal.dynatrace.com/component: operator
  name: dynatrace-oneagent-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-oneagent-csi-driver
subjects:
- kind: ServiceAccount
  name: dynatrace-oneagent-csi-driver
  namespace: dynatrace
